databases:
  - name: airplane_shop
    plan: free
    databaseName: airplane_shop
    user: enesbarut

services:
  - type: web
    plan: free
    name: airplane_shop
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn airplane_shop.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: airplane_shop
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4